Feature: Text Content Page features


  Scenario Outline: I can reach the site with admin rights
    Given I navigate to the login page
    And I log into the Touch with <username> username and <password> password with <rights> rights
    And I click on the login button
    And I go on the "Text Content" page
    Then I arrive on the Text Content Lists page
    Examples:
      | username                   | password    | rights |
      | TestAdmin@TestAdmin.com    | Igercsak8!# | admin  |
      | istvan.gercsak@metlife.com | Igercsak8!# | mixed  |

  Scenario: The right breadcrumb is appears on the page
    Given I log into the application with Jurisdiction user
    And I go on the "Text Content" page
    Then The "Text Content" breadcrumb appears


#WORK IN PROGRESS - DO NOT TEST
#
#  Scenario: New text resource content
#    Given I navigate to the login page
#    And I log into the Touch with "TestAdmin@TestAdmin.com" username and "Igercsak8!#" password
#    And I click on the login button
#    And I go on the "Text Content" page
#    And I click on the new text resource content
#    And Fields are clickable
#    And I click on the Cancel
#    And I click on the new text resource content
#    And I click on the Save

  Scenario Outline: Text content content
    Given I navigate to the login page
    And I log into the Touch with "TestAdmin@TestAdmin.com" username and "Igercsak8!#" password
    And I click on the login button
    And I go on the "Text Content" page
    And I click on the <text_id> text id
    And I can see the right <Text_locale> text locale, <text_title> title, <text_title> text title and <text_description> text description
    And I click on the modification pencil button
    And I click on the Cancel button
    And I click on the modification pencil button
    And I modify the Resource Title to <title_modification_to> and the Resource Description to <text_description_modification_to>
    And I click on the Save button
    And I can see the right <Text_locale> text locale, <title_modification_to> title, <title_modification_to> text title and <text_description_modification_to> text description
    And I click on the modification pencil button
    And I modify the Resource Title to <text_title> and the Resource Description to <text_description>
    And I click on the Save button
    And I can see the right <Text_locale> text locale, <text_title> title, <text_title> text title and <text_description> text description

    Examples:
      | text_id                                                 | Text_locale | text_title                          | text_description                                     | title_modification_to                      | text_description_modification_to                                     |
      | base:tlbl:central:about-build-number                    | en_US       | Touch build number                  | Touch build number                                   | Touch build number_test12                  | Touch build number_descriptiontest                                   |
      | base:tlbl:central:about-build-timestamp                 | en_US       | Touch build timestamp               | Touch build timestamp                                | Touch build timestamp_test13               | Touch build timestamp_descriptiontest                                |
      | base:tlbl:central:about-build-version                   | en_US       | Touch build version                 | Touch build version                                  | Touch build version_test14                 | Touch build version_descriptiontest                                  |
      | base:tlbl:central:admin-content-templates-title         | en_US       | Content Templates                   | Content Templates                                    | Content Templates_test15                   | Content Templates_descriptiontest                                    |
      | base:tlbl:central:admin-content-text-title              | en_US       | Text Content                        | Text Content                                         | Text Content_test16                        | Text Content_descriptiontest                                         |
      | base:tlbl:central:admin-jurisdictions-title             | en_US       | Manage Jurisdictions                | Manage Jurisdictions                                 | Manage Jurisdictions_test17                | Manage Jurisdictions_descriptiontest                                 |
      | base:tlbl:central:admin-system-jurisdictions-title      | en_US       | Manage Jurisdictions                | Manage Jurisdictions                                 | Manage Jurisdictions_test18                | Manage Jurisdictions_descriptiontest                                 |
      | base:tlbl:central:admin-system-users-title              | en_US       | Manage Users                        | Manage Users                                         | Manage Users_test19                        | Manage Users_descriptiontest                                         |
      | base:tlbl:central:admin-touchpoint-datalist-description | en_US       | Data List Description               | Data List Description                                | Data List Description_test20               | Data List Description_descriptiontest                                |
      | base:tlbl:central:admin-touchpoint-datalist-scope       | en_US       | Data List Scope                     | Data List Scope                                      | Data List Scope_test21                     | Data List Scope_descriptiontest                                      |
      | base:tlbl:central:admin-touchpoint-datalist-title       | en_US       | Data List Title                     | Data List Title                                      | Data List Title_test22                     | Data List Title_descriptiontest                                      |
      | base:tlbl:central:admin-touchpoint-datalists-title      | en_US       | Touchpoint Data Lists               | Touchpoint Data Lists                                | Touchpoint Data Lists_test23               | Touchpoint Data Lists_descriptiontest                                |
      | base:tlbl:central:admin-touchpoint-form-title           | en_US       | Touchpoint Form                     | Touchpoint Form                                      | Touchpoint Form_test24                     | Touchpoint Form_descriptiontest                                      |
      | base:tlbl:central:admin-touchpoint-forms-title          | en_US       | Touchpoint Forms                    | Touchpoint Forms                                     | Touchpoint Forms_test25                    | Touchpoint Forms_descriptiontest                                     |
      | base:tlbl:central:admin-users-title                     | en_US       | Manage Touch Users                  | Manage TouchUsers                                    | Manage Touch Users_test26                  | Manage TouchUsers_descriptiontest                                    |
      | base:tlbl:central:error-title                           | en_US       | An Error Has Occurred               | An Error Has Occurred                                | An Error Has Occurred_test27               | An Error Has Occurred_descriptiontest                                |
      | base:tlbl:central:form-back                             | en_US       | Back                                | Back                                                 | Back_test28                                | Back_descriptiontest                                                 |
      | base:tlbl:central:form-cancel                           | en_US       | Cancel                              | Cancel                                               | Cancel_test29                              | Cancel_descriptiontest                                               |
      | base:tlbl:central:form-description                      | en_US       | Form Description                    | Form Description                                     | Form Description_test30                    | Form Description_descriptiontest                                     |
      | base:tlbl:central:form-name                             | en_US       | Form Name                           | Form Name                                            | Form Name_test31                           | Form Name_descriptiontest                                            |
      | base:tlbl:central:form-save                             | en_US       | Save                                | Save                                                 | Save_test32                                | Save_descriptiontest                                                 |
      | base:tlbl:central:form-scope                            | en_US       | Form Scope                          | Form Scope                                           | Form Scope_test33                          | Form Scope_descriptiontest                                           |
      | base:tlbl:central:help-about-title                      | en_US       | About Touch                         | About Touch                                          | About Touch_test34                         | About Touch_descriptiontest                                          |
      | base:tlbl:central:home-intro                            | en_US       | Select one of the following options | Select one of the following options                  | Select one of the following options_test35 | Select one of the following options_descriptiontest                  |
      | base:tlbl:central:home-title                            | en_US       | Touch Central                       | Touch Central                                        | Touch Central_test36                       | Touch Central_descriptiontest                                        |
      | base:tlbl:central:jurisdiction-active                   | en_US       | Active jurisdiction                 | Toggles whether the jurisdiction is active           | Active jurisdiction_test37                 | Toggles whether the jurisdiction is active_descriptiontest           |
      | base:tlbl:central:jurisdiction-edit                     | en_US       | Edit jurisdiction                   | Edit jurisdiction                                    | Edit jurisdiction_test38                   | Edit jurisdiction_descriptiontest                                    |
      | base:tlbl:central:jurisdiction-id                       | en_US       | ID                                  | Unique identifier for a jurisdiction                 | ID_test39                                  | Unique identifier for a jurisdiction_descriptiontest                 |
      | base:tlbl:central:jurisdiction-name                     | en_US       | Name                                | Name                                                 | Name_test40                                | Name_descriptiontest                                                 |
      | base:tlbl:central:jurisdiction-new                      | en_US       | Create jurisdiction                 | Create jurisdiction                                  | Create jurisdiction_test41                 | Create jurisdiction_descriptiontest                                  |
      | base:tlbl:central:jurisdiction-url                      | en_US       | URL                                 | URL                                                  | URL_test42                                 | URL_descriptiontest                                                  |
      | base:tlbl:central:login-password                        | en_US       | Password                            | Password                                             | Password_test43                            | Password_descriptiontest                                             |
      | base:tlbl:central:login-signin                          | en_US       | Login                               | Login                                                | Login_test44                               | Login_descriptiontest                                                |
#BUG      | base:tlbl:central:login-title                | en_US       | Sign-on                   | Sign on Title             | Sign-on_test45                   | Sign on Title_descriptiontest             |
      | base:tlbl:central:login-username                        | en_US       | Username / Email                    | Username / Email                                     | Username / Email_test46                    | Username / Email_descriptiontest                                     |
      | base:tlbl:central:nav-actions                           | en_US       | Touch Central Actions               | Touch Central Actions                                | Touch Central Actions_test47               | Touch Central Actions_descriptiontest                                |
      | base:tlbl:central:nav-admin-content-title               | en_US       | Content Administration              | Content Administration                               | Content Administration_test48              | Content Administration_descriptiontest                               |
      | base:tlbl:central:nav-admin-system-title                | en_US       | System Administration               | System Administration                                | System Administration_test49               | System Administration_descriptiontest                                |
      | base:tlbl:central:nav-admin-touchpoint-title            | en_US       | Touchpoint Administration           | Touchpoint Administration                            | Touchpoint Administration_test50           | Touchpoint Administration_descriptiontest                            |
      | base:tlbl:central:nav-dashboard                         | en_US       | Dashboard                           | Reporting dashboard                                  | Dashboard_test51                           | Reporting dashboard_descriptiontest                                  |
      | base:tlbl:central:nav-help                              | en_US       | Help                                | Help                                                 | Help_test52                                | Help_descriptiontest                                                 |
      | base:tlbl:central:nav-logout                            | en_US       | Logout                              | Logout                                               | Logout_test53                              | Logout_descriptiontest                                               |
      | base:tlbl:central:reports-dashboard-title               | en_US       | Dashboards                          | Dashboards                                           | Dashboards_test54                          | Dashboards_descriptiontest                                           |
      | base:tlbl:central:reports-touch-report                  | en_US       | Touchpoints by Last Touch           | Touchpoints by Last Touch                            | Touchpoints by Last Touch_test55           | Touchpoints by Last Touch_descriptiontest                            |
      | base:tlbl:central:resource-value-add                    | en_US       | Add value                           | Add value                                            | Add value_test56                           | Add value_descriptiontest                                            |
      | base:tlbl:central:resource-value-edit                   | en_US       | Edit value                          | Edit value                                           | Edit value_test57                          | Edit value_descriptiontest                                           |
      | base:tlbl:central:resources-component                   | en_US       | Component                           | Component                                            | Component_test58                           | Component_descriptiontest                                            |
      | base:tlbl:central:resources-description                 | en_US       | Resource description                | Resource description                                 | Resource description_test59                | Resource description_descriptiontest                                 |
      | base:tlbl:central:resources-en-us-description           | en_US       | en-US Description                   | en-US Description                                    | en-US Description_test60                   | en-US Description_descriptiontest                                    |
      | base:tlbl:central:resources-individual-id               | en_US       | Individual Id                       | Individual Id                                        | Individual Id_test61                       | Individual Id_descriptiontest                                        |
      | base:tlbl:central:resources-locale                      | en_US       | Resource locale                     | Resource locale                                      | Resource locale_test62                     | Resource locale_descriptiontest                                      |
      | base:tlbl:central:resources-resource-description        | en_US       | Resource Description                | Resource description                                 | Resource Description_test63                | Resource description_descriptiontest                                 |
      | base:tlbl:central:resources-resource-enabled            | en_US       | Resource Enabled                    | Resource Enabled                                     | Resource Enabled_test64                    | Resource Enabled_descriptiontest                                     |
      | base:tlbl:central:resources-resource-title              | en_US       | Resource Title                      | Resource Title                                       | Resource Title_test65                      | Resource Title_descriptiontest                                       |
      | base:tlbl:central:resources-scope                       | en_US       | Scope                               | Scope                                                | Scope_test66                               | Scope_descriptiontest                                                |
      | base:tlbl:central:resources-title                       | en_US       | Resource title                      | Resource title                                       | Resource title_test67                      | Resource title_descriptiontest                                       |
      | base:tlbl:central:resources-type                        | en_US       | Resource Type                       | Resource type                                        | Resource Type_test68                       | Resource type_descriptiontest                                        |
      | base:tlbl:central:touch-user-confirm-password           | en_US       | Confirm New Password                | Confirm New Password                                 | Confirm New Password_test69                | Confirm New Password_descriptiontest                                 |
      | base:tlbl:central:touch-user-password                   | en_US       | New Password                        | New Password                                         | New Password_test70                        | New Password_descriptiontest                                         |
      | base:tlbl:central:user-create-password-title            | en_US       | Create New Password                 | Create New Password                                  | Create New Password_test71                 | Create New Password_descriptiontest                                  |
      | base:tlbl:central:user-profile-title                    | en_US       | User Profile                        | User Profile                                         | User Profile_test72                        | User Profile_descriptiontest                                         |
      | base:tlbl:central:users-edit-roles-title                | en_US       | Manage Touch User Roles             | Manage Touch User Roles                              | Manage Touch User Roles_test73             | Manage Touch User Roles_descriptiontest                              |
      | base:tlbl:central:users-edit-user-title                 | en_US       | Edit Touch User                     | Edit Touch User                                      | Edit Touch User_test74                     | Edit Touch User_descriptiontest                                      |
      | base:tlbl:central:users-send-token-title                | en_US       | Touch User Registration Token       | Touch User Registration Token                        | Touch User Registration Token_test75       | Touch User Registration Token_descriptiontest                        |
      | base:tlbl:central:users-user-active                     | en_US       | Active                              | Active                                               | Active_test76                              | Active_descriptiontest                                               |
      | base:tlbl:central:users-user-central-admin              | en_US       | Touch Central Admin                 | Touch Central Admin                                  | Touch Central Admin_test77                 | Touch Central Admin_descriptiontest                                  |
      | base:tlbl:central:users-user-central-roles              | en_US       | Touch Central Roles                 | Touch Central Roles                                  | Touch Central Roles_test78                 | Touch Central Roles_descriptiontest                                  |
      | base:tlbl:central:users-user-details                    | en_US       | User details                        | User details                                         | User details_test79                        | User details_descriptiontest                                         |
      | base:tlbl:central:users-user-email                      | en_US       | Email                               | Email                                                | Email_test80                               | Email_descriptiontest                                                |
      | base:tlbl:central:users-user-firstname                  | en_US       | First Name                          | Full Name                                            | First Name_test81                          | Full Name_descriptiontest                                            |
      | base:tlbl:central:users-user-fullname                   | en_US       | Full Name                           | Full Name                                            | Full Name_test82                           | Full Name_descriptiontest                                            |
      | base:tlbl:central:users-user-id                         | en_US       | Id                                  | Id                                                   | Id_test83                                  | Id_descriptiontest                                                   |
      | base:tlbl:central:users-user-jurisdiction-admin         | en_US       | Jurisdiction Admin                  | Jurisdiction Roles                                   | Jurisdiction Admin_test84                  | Jurisdiction Roles_descriptiontest                                   |
      | base:tlbl:central:users-user-lastname                   | en_US       | Full Name                           | Last Name                                            | Full Name_test85                           | Last Name_descriptiontest                                            |
      | base:tlbl:central:users-user-manage-roles               | en_US       | Manage roles                        | Manage roles                                         | Manage roles_test86                        | Manage roles_descriptiontest                                         |
      | base:tlbl:central:users-user-new                        | en_US       | Create Touch User                   | Create Touch User                                    | Create Touch User_test87                   | Create Touch User_descriptiontest                                    |
      | base:tlbl:central:users-user-registered                 | en_US       | Registration Date                   | Registration Date                                    | Registration Date_test88                   | Registration Date_descriptiontest                                    |
      | base:tlbl:central:users-user-registration               | en_US       | Registration                        | Registration                                         | Registration_test89                        | Registration_descriptiontest                                         |
      | base:tlbl:central:users-user-role-memberships           | en_US       | Role Memberships                    | Role Memberships                                     | Role Memberships_test90                    | Role Memberships_descriptiontest                                     |
      | base:tlbl:central:users-user-send-registration-token    | en_US       | Send registration token             | Send registration token                              | Send registration token_test91             | Send registration token_descriptiontest                              |
      | base:tlbl:zone:about-build-number                       | en_US       | Build Number                        | Build Number                                         | Build Number_test92                        | Build Number_descriptiontest                                         |
      | base:tlbl:zone:about-build-timestamp                    | en_US       | Build Time Stamp                    | Build Time Stamp                                     | Build Time Stamp_test93                    | Build Time Stamp_descriptiontest                                     |
      | base:tlbl:zone:contact-create-new                       | en_US       | Create New Contact                  | Create New Contact                                   | Create New Contact_test94                  | Create New Contact_descriptiontest                                   |
      | base:tlbl:zone:contact-first-name                       | en_US       | First Name                          | Contact First Name                                   | First Name_test95                          | Contact First Name_descriptiontest                                   |
      | base:tlbl:zone:contact-last-name                        | en_US       | Last Name                           | Contact Last Name                                    | Last Name_test96                           | Contact Last Name_descriptiontest                                    |
      | base:tlbl:zone:contact-no-results                       | en_US       | No Results Found                    | No Results Found                                     | No Results Found_test97                    | No Results Found_descriptiontest                                     |
      | base:tlbl:zone:contact-search                           | en_US       | Search for a Contact                | Search for a Contact                                 | Search for a Contact_test98                | Search for a Contact_descriptiontest                                 |
      | base:tlbl:zone:form-action-save                         | en_US       | Save                                | Save                                                 | Save_test99                                | Save_descriptiontest                                                 |
      | base:tlbl:zone:form-cancel                              | en_US       | Cancel                              | Cancel                                               | Cancel_test100                             | Cancel_descriptiontest                                               |
      | base:tlbl:zone:form-save                                | en_US       | Save                                | Save                                                 | Save_test101                               | Save_descriptiontest                                                 |
      | base:tlbl:zone:help-about-title                         | en_US       | About Touch                         | About Touch                                          | About Touch_test102                        | About Touch_descriptiontest                                          |
      | base:tlbl:zone:nav-dashboard                            | en_US       | Dashboard                           | Dashboard                                            | Dashboard_test103                          | Dashboard_descriptiontest                                            |
      | base:tlbl:zone:nav-help                                 | en_US       | Help                                | Help                                                 | Help_test104                               | Help_descriptiontest                                                 |
      | base:tlbl:zone:nav-logout                               | en_US       | Logout                              | Logout                                               | Logout_test105                             | Logout_descriptiontest                                               |
      | base:tlbl:zone:nav-reports                              | en_US       | Reports                             | Reports                                              | Reports_test106                            | Reports_descriptiontest                                              |
      | base:tlbl:zone:results-contact                          | en_US       | Contact Details                     | Contact Details                                      | Contact Details_test107                    | Contact Details_descriptiontest                                      |
      | base:tlbl:zone:results-last-touch                       | en_US       | Last Touch                          | Last Touch                                           | Last Touch_test108                         | Last Touch_descriptiontest                                           |
      | base:tlbl:zone:results-no-results                       | en_US       | No Results Found                    | No Results Found                                     | No Results Found_test109                   | No Results Found_descriptiontest                                     |
      | base:tlbl:zone:results-product-category                 | en_US       | Product Category                    | Product Category                                     | Product Category_test110                   | Product Category_descriptiontest                                     |
      | base:tlbl:zone:results-product-name                     | en_US       | Product Name                        | Product Name                                         | Product Name_test111                       | Product Name_descriptiontest                                         |
      | base:tlbl:zone:searchbar-search                         | en_US       | Search for name or reference        | Search for First Name, Last Name, email or reference | Search for name or reference_test112       | Search for First Name, Last Name, email or reference_descriptiontest |
      | base:tlbl:zone:show-external                            | en_US       | Show Customer View                  | Show Customer View                                   | Show Customer View_test113                 | Show Customer View_descriptiontest                                   |
      | base:tlbl:zone:tac-backlink                             | en_US       | Back                                | Back                                                 | Back_test114                               | Back_descriptiontest                                                 |
      | base:tlbl:zone:tac-title                                | en_US       | Terms & Conditions                  | Terms & Conditions                                   | Terms & Conditions_test115                 | Terms & Conditions_descriptiontest                                   |
      | base:tlbl:zone:touchpoint-new                           | en_US       | Create New Touchpoint               | Create New Touchpoint                                | Create New Touchpoint_test116              | Create New Touchpoint_descriptiontest                                |
      | base:tlbl:zone:touchpoint-title                         | en_US       | Touchpoint                          | Touchpoint                                           | Touchpoint_test117                         | Touchpoint_descriptiontest                                           |
      | base:tlbl:zone:touchpoint-updates                       | en_US       | Touchpoint Updates                  | Touchpoint Updates                                   | Touchpoint Updates_test118                 | Touchpoint Updates_descriptiontest                                   |
      | base:tlbl:zone:update-add                               | en_US       | Add Update                          | Add Update                                           | Add Update_test119                         | Add Update_descriptiontest                                           |
      | base:tlbl:zone:update-comment                           | en_US       | Internal Comment                    | Internal Comment                                     | Internal Comment_test120                   | Internal Comment_descriptiontest                                     |
      | base:tlbl:zone:update-notification                      | en_US       | Send Notification                   | Send Notification                                    | Send Notification_test121                  | Send Notification_descriptiontest                                    |
      | base:tlbl:zone:update-selector-external                 | en_US       | Customer Facing Update              | Customer Facing Update                               | Customer Facing Update_test122             | Customer Facing Update_descriptiontest                               |
      | base:tlbl:zone:update-selector-internal                 | en_US       | Internal Update                     | Internal Update                                      | Internal Update_test123                    | Internal Update_descriptiontest                                      |
      | base:tlbl:zone:update-title                             | en_US       | Add New Update                      | Add New Update                                       | Add New Update_test124                     | Add New Update_descriptiontest                                       |
      | base:tlbl:zone:updates-title                            | en_US       | Touchpoint Updates                  | Touchpoint Updates                                   | Touchpoint Updates_test125                 | Touchpoint Updates_descriptiontest                                   |
      | base:tlbl:zone:user-profile-title                       | en_US       | User Profile                        | User Profile                                         | User Profile_test126                       | User Profile_descriptiontest                                         |
